name: 🚀 Submit Automation Module
description: Submit your automation module to the Supra AutoFi Marketplace
title: "[MODULE SUBMISSION] "
labels: ["module-submission", "pending-review"]
body:
  - type: markdown
    attributes:
      value: |
        ## Submit Your Automation Module
        Thank you for contributing to the Supra AutoFi Marketplace! Please fill out the form below.
        
        **Before submitting:**
        - Ensure your module is deployed on Supra testnet
        - Your GitHub repository should include complete source code and documentation
        - Test your module thoroughly before submission

  - type: input
    id: module-name
    attributes:
      label: Module Name
      description: A clear, descriptive name for your automation module
      placeholder: e.g., "Auto Wallet TopUp"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description of what your module does (1-2 sentences)
      placeholder: Explain the functionality and use case of your module
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Select the category that best fits your module
      options:
        - DeFi
        - Gaming
        - Utility
        - NFT
        - DAO
    validations:
      required: true

  - type: input
    id: address
    attributes:
      label: Deployment Address
      description: The Supra testnet address where your module is deployed
      placeholder: "0x..."
    validations:
      required: true

  - type: input
    id: module-id
    attributes:
      label: Module ID
      description: The exact module name/identifier
      placeholder: "e.g., auto_topup"
    validations:
      required: true

  - type: input
    id: github-repo
    attributes:
      label: GitHub Repository
      description: Link to your module's source code
      placeholder: "https://github.com/username/repo"
    validations:
      required: true

  - type: input
    id: contributor
    attributes:
      label: Contributor Name
      description: Your name or organization name
      placeholder: "e.g., SupraLabs"
    validations:
      required: true

  - type: checkboxes
    id: requirements
    attributes:
      label: Submission Requirements
      description: Please confirm the following
      options:
        - label: My module is deployed and tested on Supra testnet
          required: true
        - label: My GitHub repository includes complete source code
          required: true
        - label: My repository includes documentation (README)
          required: true
        - label: I have tested all entry functions
          required: true
        - label: My code follows Supra Move best practices
          required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any additional details, special requirements, or notes
      placeholder: Optional additional context

  - type: markdown
    attributes:
      value: |
        ---
        ## What happens next?
        1. ✅ Our team will review your submission
        2. 🔍 We'll test your module on testnet
        3. 📝 You may receive feedback or requests for changes
        4. 🎉 Once approved, your module will be added to the marketplace
        
        **Review time:** Usually 2-5 business days
        
        Thank you for contributing to Supra AutoFi! 🚀